cookie:
  expiry_days: 2
  key: some_signature_key
  name: tulipauth
credentials:
  usernames:
    admin1:
      location: Kota
      name: admin1
      password: $2b$12$XLJUl8l4YFf3gLN2b03P.uh67KxhIf4LyTVHMsy/oU9ODnLNmaNqO
      role: admin
    tulip:
      location: Pune
      name: Tulip
      password: $2b$12$t6E6UlTLByLPytO51P8bkueNSz4lToy4/4qeORlpPckFn04H0prTm
      role: master
    user1:
      name: user1
      password: $2b$12$gBCf40G1pf/.KaYFTsOfIO0B/WE5OjmxGZxetToLS6l7sJovCm4Y6
      role: user
    bc01:
      name: BC01
      password: $2b$12$gwIWxa9DTtO80/HXeYhldOC0lgo46AaP3ANuJ1DvTJaWkzLyOBea2
      role: user
    bc02:
      name: BC02
      password: $2b$12$Ee5iuBO.BpgLd6gfSHtHsuw2BIETvG./HQRyXrTcs3MSRs7v8axCK
      role: user
    bc03:
      name: BC03
      password: $2b$12$9Ph0URcfUQoYfBT6qqeK.eVd4o6qB11Nm7.fpz0ZM2A2.0Ha2/hA6
      role: user
    bc04:
      name: bc04
      password: $2b$12$L7DEmGkdKW62QNGZLjsd6OGDGZWdokiW7cs7LgvaeD7goCPfAnWs2
      role: user
    bc05:
      name: bc05
      password: $2b$12$5u0YjDY2Z7EsMMas.BOWVOa6NBMVJmCMaYo4XpxmNtWIeL9lo7.dW
      role: user
    bc06:
      name: bc06
      password: $2b$12$FB5nabFrfd9B0LsOgsjE9.dYTclgpiDFFv/IGBwc2qlQ81F8iJUDi
      role: user
    bc07:
      name: bc07
      password: $2b$12$p0ems/219sPRjR04HPak.exA4xrKnfecl/SaO72BnpEpB07XLTNtq
      role: user
    bc08:
      name: bc08
      password: $2b$12$c6hMlzIVHDOzxdGpkN8AdOeIjMRXm1tFtNWKDoqUHRfV5/v1fxwoC
      role: user
    bc09:
      name: bc09
      password: $2b$12$Dzp62ScC1nEAGm01apC.WOEQXyhRwlcsqsOo12yD/AadhNNbFv6n2
      role: user
    bc10:
      name: bc10
      password: $2b$12$M36sIa7Q5vLgyZWbYdkWaeB7NIP3apNQ8gTgF36Z4uJrQErfFfqxe
      role: user
    sudish:
      name: sudish
      password: $2b$12$AsIRXyiZGgC0TxU2.t0lf.M.SSyKZCLYhUHkPu2Ja/ZEBp9tDZSB.
      role: admin
    tf01:
      name: NBCFDC
      password: $2b$12$t8A6H2BQsusjzDt1/lhfuOofQUKUU1dSBHISITNEvXT1S5eSEuRwi
      role: user
    tf02:
      name: NBCFDC
      password: $2b$12$Y.2G/oUQiKN/lTAPysSMceFNH2shY2D85a3ghTgnYD2ohKBhfLIhS
      role: user
    tf03:
      name: NBCFDC
      password: $2b$12$1QEiadthlIXIsXiVsFTvpu2SGT0evQduAFVeeYHVzgcnzQLHKVh8O
      role: user
    tf04:
      name: NSFDC
      password: $2b$12$/OG.XSF.JIwmGjIkucm5GebTWKXeeFDCF8nxgInasayyRlJAwaNm6
      role: user
    tf05:
      name: NSFDC
      password: $2b$12$S7D8uszyFXgnFco/Z7XJhe1BDLMpYVBnT.5kSdPfNiaDTAAqvUhaq
      role: user
    tf06:
      name: NSFDC
      password: $2b$12$1YV9cejIv5IpXTWfg8yXxOPMkEsL1L9WuEbJ79hdvQR0Aol3Sm6xq
      role: user
    tf07:
      name: NSKFDC
      password: $2b$12$Jnh2EF0hfJBjVXEk5dsIH..6zFF/9w5Sp3wPXtZCqZCOdpKjDBeVK
      role: user
    TF08:
      name: NSKFDC
      password: $2b$12$46tvElYOYdOuzO4PjjjVIOBCv3/wCiOm3GIU9h3gvbblenQiL8PRS
      role: user
gst_number: 07AABCN8953B1ZI
